name: release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  id-token: write   # OIDC
  contents: write   # create GitHub release

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
      - run: cargo semver-checks check-release # ensure correct version format
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish --token ${{ steps.auth.outputs.token }}
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
